on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # When running `act`, use node_modules code directly, unless `--env USE_DIST=1` specified
      - if: ${{ env.ACT && !env.USE_DIST }}
        uses: ./test

      - if: ${{ !env.ACT || env.USE_DIST }}
        uses: ./.

      - uses: actions/cache@v4
        with:
          key: testfile
          path: package.json
      - run: |
          curl -v http://127.0.0.1:8080/testfile
      - run: |
          echo "Hi" > "$RUNNER_TEMP/gha-nix-cache/upload/hello"
      - run: |
          find "$RUNNER_TEMP/gha-nix-cache" -ls
      - if: always()
        run: |
          cat "$RUNNER_TEMP/gha-nix-cache/stderr.log"
