on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.
      - run: |
          curl -v http://127.0.0.1:8080/testfile
      - run: |
          echo "Hi" > $RUNNER_TEMP/gha-nix-cache/upload/hello
      - run: |
          find $RUNNER_TEMP/gha-nix-cache -ls
      - if: always()
        run: |
          cat $RUNNER_TEMP/gha-nix-cache/stderr.log
